# WIRTHFORGE Event Log Audit Trail Example
# WF-TECH-004 State Management & Storage System
# This file demonstrates the structure and content of a session event log
# for audit, debugging, and deterministic replay purposes.

session_metadata:
  session_id: "20250817T194800Z_001"
  user_id: "default"
  start_time: "2025-08-17T19:48:00.000000Z"
  end_time: "2025-08-17T19:52:15.456789Z"
  duration_seconds: 255.456789
  hardware_tier: "mid"
  session_mode: "normal"
  total_energy: 1247.8
  total_events: 1567
  clean_shutdown: true
  schema_version: "1.0.0"

# Event log entries in chronological order
# Each event captures a discrete occurrence with full context
events:
  - event_id: 1
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:00.123456Z"
    type: "system.start"
    data:
      version: "1.0.0"
      user_id: "default"
      model_id: "ollama/llama2:7b"
      hardware_tier: "mid"
      mode: "offline"
      features_enabled:
        - "parallel_processing"
        - "interference_detection" 
        - "resonance_detection"
      config:
        frame_rate: 60
        energy_threshold: 0.1
        batch_size: 15
    # Commentary: Session initialization with system configuration

  - event_id: 2
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.130000Z"
    type: "user.prompt"
    data:
      prompt_id: "prompt_abc123"
      interface: "text"
      length: 45
      truncated: false
      hash: "a1b2c3d4e5f67890abcdef1234567890abcdef12"
      language: "en"
      intent: "question"
    # Commentary: User initiated conversation with text prompt
    # Hash preserves privacy while enabling audit verification

  - event_id: 3
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.150000Z"
    type: "energy.update"
    frame_id: 1
    data:
      energy: 4.2
      accumulator: 4.2
      model_id: "ollama/llama2:7b"
      fps: 60.0
      frame_budget_used: 12.3
      diversity_index: 0.0
      token_count: 0
    # Commentary: First energy measurement as AI begins processing
    # Frame budget usage well within 16.67ms limit

  - event_id: 4
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.167000Z"
    type: "ai.output"
    data:
      token: "Hello"  # In privacy mode, this would be token_hash instead
      prompt_id: "prompt_abc123"
      token_index: 1
      is_last: false
      model_id: "ollama/llama2:7b"
      logprobs: [-0.1, -0.3, -0.8]
      entropy: 1.23
      generation_time_ms: 15.2
    # Commentary: First token generated by AI model
    # Includes probability and timing information for analysis

  - event_id: 5
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.183000Z"
    type: "energy.update"
    frame_id: 2
    data:
      energy: 5.0
      accumulator: 9.2
      model_id: "ollama/llama2:7b"
      fps: 60.0
      frame_budget_used: 14.1
      diversity_index: 0.0
      token_count: 1
    # Commentary: Energy increased due to token generation
    # Accumulator tracks running total for session

  - event_id: 6
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.200000Z"
    type: "ai.output"
    data:
      token: "there!"
      prompt_id: "prompt_abc123"
      token_index: 2
      is_last: true
      model_id: "ollama/llama2:7b"
      logprobs: [-0.05, -0.12]
      entropy: 0.89
      generation_time_ms: 12.8
    # Commentary: Final token in response sequence

  - event_id: 7
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:48:05.215000Z"
    type: "ai.response_complete"
    data:
      prompt_id: "prompt_abc123"
      model_id: "ollama/llama2:7b"
      total_tokens: 2
      total_energy: 5.0
      generation_time_ms: 28.0
      tokens_per_second: 71.4
      completion_reason: "finished"
    # Commentary: Response generation completed successfully
    # Performance metrics captured for optimization

  # ... [Additional events would continue chronologically] ...

  - event_id: 234
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:49:23.456789Z"
    type: "pattern.interference"
    frame_id: 4567
    data:
      models_involved: ["ollama/llama2:7b", "ollama/mistral:7b"]
      interference_type: "constructive"
      strength: 0.73
      frequency: 42.5
      duration_ms: 150.0
    # Commentary: Interference pattern detected between two models
    # Constructive interference amplifies energy output

  - event_id: 235
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:49:23.612000Z"
    type: "energy.peak"
    frame_id: 4578
    data:
      energy: 15.7
      threshold: 12.0
      model_id: "ollama/llama2:7b"
      context: "interference_amplification"
    # Commentary: Energy peak triggered by interference pattern
    # Exceeds normal threshold due to constructive interference

  - event_id: 456
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:50:45.123000Z"
    type: "pattern.resonance"
    frame_id: 9876
    data:
      models_involved: ["ollama/llama2:7b", "ollama/mistral:7b", "ollama/codellama:7b"]
      resonance_frequency: 440.0
      amplitude: 0.92
      synchronization_level: 0.88
      harmony_detected: true
      energy_amplification: 2.34
    # Commentary: Three-model resonance achieved
    # High synchronization creates significant energy amplification

  - event_id: 457
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:50:45.125000Z"
    type: "experience.celebration"
    data:
      celebration_type: "resonance_achieved"
      intensity: "spectacular"
      visual_effects: ["aurora_burst", "harmonic_waves", "energy_cascade"]
      duration_ms: 3000
      trigger_data:
        resonance_frequency: 440.0
        models_count: 3
        energy_amplification: 2.34
    # Commentary: UI celebration triggered by resonance achievement
    # Spectacular visual effects for 3-second duration

  - event_id: 789
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:51:30.000000Z"
    type: "state.snapshot_created"
    data:
      snapshot_id: 42
      snapshot_type: "periodic"
      state_size_bytes: 4096
      events_since_last: 333
      compression_ratio: 0.73
    # Commentary: Periodic snapshot for crash recovery
    # State compressed to 73% of original size

  - event_id: 1234
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:52:00.000000Z"
    type: "health.heartbeat"
    data:
      system_health: "healthy"
      fps: 59.8
      memory_usage_mb: 2048
      disk_usage_mb: 156
      active_connections: 1
      event_queue_size: 8
      models_loaded: ["ollama/llama2:7b", "ollama/mistral:7b", "ollama/codellama:7b"]
    # Commentary: Regular health check shows system performing well
    # FPS slightly below 60 but within acceptable range

  - event_id: 1566
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:52:15.400000Z"
    type: "user.action"
    data:
      action: "stop"
      context:
        reason: "session_complete"
        satisfaction_rating: 5
      ui_element: "stop_button"
    # Commentary: User initiated session termination
    # High satisfaction rating indicates successful session

  - event_id: 1567
    session_id: "20250817T194800Z_001"
    timestamp: "2025-08-17T19:52:15.456789Z"
    type: "system.end"
    data:
      duration_ms: 255456.789
      total_energy: 1247.8
      total_events: 1567
      clean_shutdown: true
      reason: "user_exit"
    # Commentary: Session ended cleanly by user request
    # All metrics captured for user progress tracking

# Snapshot references for recovery
snapshots:
  - snapshot_id: 42
    timestamp: "2025-08-17T19:51:30.000000Z"
    snapshot_type: "periodic"
    last_event_id: 789
    energy_accumulator: 1089.3
    frame_count: 9876
    state_summary:
      active_models: 3
      interference_events: 12
      resonance_events: 5
      peak_energy: 15.7
      avg_fps: 59.9

# Audit trail summary
audit_summary:
  total_events: 1567
  event_types:
    "system.*": 2
    "user.*": 45
    "ai.*": 892
    "energy.*": 456
    "pattern.*": 17
    "experience.*": 8
    "health.*": 12
    "state.*": 3
    "error": 0
  
  data_integrity:
    missing_events: 0
    invalid_timestamps: 0
    schema_violations: 0
    orphaned_events: 0
  
  performance_metrics:
    avg_logging_latency_ms: 2.3
    max_logging_latency_ms: 8.7
    frame_drops: 2
    queue_overruns: 0
  
  privacy_compliance:
    raw_text_stored: false  # Privacy mode enabled
    user_data_hashed: true
    export_available: true
    deletion_possible: true

# Usage notes for audit and replay:
# 1. Events are ordered chronologically by timestamp
# 2. Each event contains complete context for deterministic replay
# 3. Energy accumulator can be verified by summing energy.update events
# 4. Frame timing can be validated against 60Hz target (16.67ms budget)
# 5. Pattern events correlate with energy peaks for validation
# 6. User privacy is preserved through hashing sensitive content
# 7. Complete session state can be reconstructed from this log
# 8. Snapshots provide fast recovery points during replay
# 9. Health events indicate system performance throughout session
# 10. Clean shutdown ensures data integrity and completeness
